Education\VisualFeedbackBundle\Entity\Expressivevocabquestion:
  type: entity
  table: ExpressiveVocabQuestion
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    orderIndex:
      type: integer
      unsigned: false
      nullable: true
      column: order_index
    name:
      type: string
      length: 128
      fixed: false
      nullable: true
    text:
      type: string
      length: 128
      fixed: false
      nullable: true
  oneToOne:
    image:
      targetEntity: Image
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Image_id:
          referencedColumnName: id
      orphanRemoval: false
    lesson:
      targetEntity: Lesson
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Lesson_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
