Education\VisualFeedbackBundle\Entity\Imagefolder:
  type: entity
  table: ImageFolder
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 128
      fixed: false
      nullable: true
    rootPath:
      type: string
      length: 1024
      fixed: false
      nullable: true
      column: root_path
  lifecycleCallbacks: {  }
