Education\VisualFeedbackBundle\Entity\Image:
  type: entity
  table: Image
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    label:
      type: string
      length: 128
      fixed: false
      nullable: true
    filename:
      type: string
      length: 256
      fixed: false
      nullable: true
  oneToOne:
    imagefolder:
      targetEntity: Imagefolder
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ImageFolder_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
