Education\VisualFeedbackBundle\Entity\Imagequestion:
  type: entity
  table: ImageQuestion
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 128
      fixed: false
      nullable: true
    text:
      type: string
      length: 128
      fixed: false
      nullable: true
  oneToOne:
    image:
      targetEntity: Image
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Image_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
