Education\VisualFeedbackBundle\Entity\Image:
  type: entity
  table: Image
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    label:
      type: string
      length: 128
      fixed: false
      nullable: true
    type:
      type: string
      length: 128
      fixed: false
      nullable: false
    filename:
      type: string
      length: 256
      fixed: false
      nullable: true
    localPath:
      type: string
      length: 512
      fixed: false
      nullable: true
      column: local_path
    webPath:
      type: string
      length: 512
      fixed: false
      nullable: true
      column: web_path
  lifecycleCallbacks: {  }
