Education\VisualFeedbackBundle\Entity\Lesson:
  type: entity
  table: Lesson
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 128
      fixed: false
      nullable: true
    type:
      type: string
      length: 128
      fixed: false
      nullable: true
    lessonPlan:
      type: string
      length: 128
      fixed: false
      nullable: true
      column: lesson_plan
    subject:
      type: string
      length: 128
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
