Education\VisualFeedbackBundle\Entity\LessonImagequestion:
  type: entity
  table: Lesson_ImageQuestion
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    orderIndex:
      type: integer
      unsigned: false
      nullable: false
      column: order_index
  oneToOne:
    imagequestion:
      targetEntity: Imagequestion
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ImageQuestion_id:
          referencedColumnName: id
      orphanRemoval: false
    lessonplanLesson:
      targetEntity: LessonplanLesson
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        LessonPlan_Lesson_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
