Education\VisualFeedbackBundle\Entity\Pupilanswer:
  type: entity
  table: PupilAnswer
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    imageAnswer:
      type: string
      length: 45
      fixed: false
      nullable: true
      column: image_answer
    textAnswer:
      type: string
      length: 45
      fixed: false
      nullable: true
      column: text_answer
    timestamp:
      type: integer
      unsigned: false
      nullable: false
  oneToOne:
    question:
      targetEntity: Question
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Question_id:
          referencedColumnName: id
      orphanRemoval: false
    tutoringsession:
      targetEntity: Tutoringsession
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        TutoringSession_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
