Education\VisualFeedbackBundle\Entity\Question:
  type: entity
  table: Question
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 128
      fixed: false
      nullable: true
    text:
      type: string
      length: 128
      fixed: false
      nullable: true
    type:
      type: string
      length: 128
      fixed: false
      nullable: true
  oneToOne:
    image:
      targetEntity: Image
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Image_id:
          referencedColumnName: id
      orphanRemoval: false
    lesson:
      targetEntity: Lesson
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Lesson_id:
          referencedColumnName: id
      orphanRemoval: false
    audio:
      targetEntity: Audio
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Audio_id:
          referencedColumnName: id
      orphanRemoval: false
    pupilanswer:
      targetEntity: Pupilanswer
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        PupilAnswer_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
