Education\VisualFeedbackBundle\Entity\Receptivevocabimage:
  type: entity
  table: ReceptiveVocabImage
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    receptivevocabquestion:
      targetEntity: Receptivevocabquestion
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ReceptiveVocabQuestion_id:
          referencedColumnName: id
      orphanRemoval: false
    image:
      targetEntity: Image
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Image_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
