Education\VisualFeedbackBundle\Entity\Receptivevocabquestion:
  type: entity
  table: ReceptiveVocabQuestion
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 45
      fixed: false
      nullable: true
  oneToOne:
    lesson:
      targetEntity: Lesson
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Lesson_id:
          referencedColumnName: id
      orphanRemoval: false
    audio:
      targetEntity: Audio
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Audio_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
