Education\VisualFeedbackBundle\Entity\Statuscode:
  type: entity
  table: StatusCode
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 128
      fixed: false
      nullable: false
    description:
      type: string
      length: 1024
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
