Education\VisualFeedbackBundle\Entity\SubjectLessonplan:
  type: entity
  table: Subject_LessonPlan
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    subject:
      targetEntity: Subject
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Subject_id:
          referencedColumnName: id
      orphanRemoval: false
    lessonplan:
      targetEntity: Lessonplan
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        LessonPlan_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
