Education\VisualFeedbackBundle\Entity\Tutor:
  type: entity
  table: Tutor
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    firstName:
      type: string
      length: 128
      fixed: false
      nullable: false
      column: first_name
    middleName:
      type: string
      length: 128
      fixed: false
      nullable: true
      column: middle_name
    lastName:
      type: string
      length: 128
      fixed: false
      nullable: false
      column: last_name
  oneToOne:
    image:
      targetEntity: Image
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Image_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
