Education\VisualFeedbackBundle\Entity\Tutoringsession:
  type: entity
  table: TutoringSession
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    hash:
      type: string
      length: 256
      fixed: false
      nullable: false
    status:
      type: string
      length: 128
      fixed: false
      nullable: true
  oneToOne:
    lesson:
      targetEntity: Lesson
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Lesson_id:
          referencedColumnName: id
      orphanRemoval: false
    pupil:
      targetEntity: Pupil
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Pupil_id:
          referencedColumnName: id
      orphanRemoval: false
    tutor:
      targetEntity: Tutor
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Tutor_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
