config_ie:
    pattern:  /config/ie
    defaults: { _controller: EducationVisualFeedbackBundle:Config:ie }




config_index:
    pattern:  /config/
    defaults: { _controller: EducationVisualFeedbackBundle:Config:index }

config_index2:
    pattern:  /config/index
    defaults: { _controller: EducationVisualFeedbackBundle:Config:index }





config_image_update:
    pattern:  /config/update/image
    defaults: { _controller: EducationVisualFeedbackBundle:Config:updateImage }

config_image_upload:
    pattern:  /config/upload/image
    defaults: { _controller: EducationVisualFeedbackBundle:Config:uploadImage }

config_image_list:
    pattern:  /config/list/image.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listImage }




config_audio_update:
    pattern:  /config/update/audio
    defaults: { _controller: EducationVisualFeedbackBundle:Config:updateAudio }

config_audio_upload:
    pattern:  /config/upload/audio
    defaults: { _controller: EducationVisualFeedbackBundle:Config:uploadAudio }

config_audio_list:
    pattern:  /config/list/audio.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listAudio }



config_pupil_list:
    pattern:  /config/list/pupil.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listPupil }

config_pupil_icon_list:
    pattern:  /config/list/pupil/icon.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listPupilIcon }

config_pupil_create:
    pattern:  /config/create/pupil
    defaults: { _controller: EducationVisualFeedbackBundle:Config:createPupil }




config_tutor_list:
    pattern:  /config/list/tutor.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listTutor }

config_tutor_icon_list:
    pattern:  /config/list/tutor/icon.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listTutorIcon }

config_tutor_create:
    pattern:  /config/create/tutor
    defaults: { _controller: EducationVisualFeedbackBundle:Config:createTutor }

config_tutor_update:
    pattern:  /config/update/tutor
    defaults: { _controller: EducationVisualFeedbackBundle:Config:updateTutor }





config_subject_list:
    pattern:  /config/list/subject.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listSubject }


config_lesson_plan_list:
    pattern:  /config/list/lessonplan.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listLessonPlan }



config_lesson_list:
    pattern:  /config/list/lesson.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listLesson }

config_lesson_image_list:
    pattern:  /config/list/lessonImage.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listLessonImage }

config_lesson_create:
    pattern:  /config/create/lesson
    defaults: { _controller: EducationVisualFeedbackBundle:Config:createLesson }

config_lesson_update:
    pattern:  /config/update/lesson
    defaults: { _controller: EducationVisualFeedbackBundle:Config:updateLesson }





config_session_list:
    pattern:  /config/list/session.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listSession }

config_session_create:
    pattern:  /config/create/session
    defaults: { _controller: EducationVisualFeedbackBundle:Config:createSession }




config_setting_update:
    pattern:  /config/update/setting
    defaults: { _controller: EducationVisualFeedbackBundle:Config:updateSetting }



tutor_index:
    pattern:  /tutor/index
    defaults: { _controller: EducationVisualFeedbackBundle:Tutor:index }


pupil_index:
    pattern:  /pupil/index
    defaults: { _controller: EducationVisualFeedbackBundle:Pupil:index }

pupil_lesson_index:
    pattern:  /pupil/lesson
    defaults: { _controller: EducationVisualFeedbackBundle:Pupil:lesson }

pupil_session_list:
    pattern:  /pupil/list/session.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listSession }

pupil_session_get:
    pattern:  /pupil/get/session.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:getSession }

pupil_navigate:
    pattern:  /pupil/navigate
    defaults: { _controller: EducationVisualFeedbackBundle:Pupil:navigateSession }

pupil_answer:
    pattern:  /pupil/answer
    defaults: { _controller: EducationVisualFeedbackBundle:Pupil:answer }


report_index:
    pattern:  /report/
    defaults: { _controller: EducationVisualFeedbackBundle:Report:index }

report_index2:
    pattern:  /report/index
    defaults: { _controller: EducationVisualFeedbackBundle:Report:index }

pupil_session_list:
    pattern:  /report/list/session.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listSession }

report_lesson_list:
    pattern:  /report/list/lesson.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listLesson }

report_subject_list:
    pattern:  /report/list/subject.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listSubject }

report_lesson_plan_list:
    pattern:  /report/list/lessonplan.{_format}
    defaults: { _controller: EducationVisualFeedbackBundle:Config:listLessonPlan }











